/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { FullMathTest } from "../FullMathTest";

export class FullMathTest__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<FullMathTest> {
    return super.deploy(overrides || {}) as Promise<FullMathTest>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): FullMathTest {
    return super.attach(address) as FullMathTest;
  }
  connect(signer: Signer): FullMathTest__factory {
    return super.connect(signer) as FullMathTest__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FullMathTest {
    return new Contract(address, _abi, signerOrProvider) as FullMathTest;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "y",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "z",
        type: "uint256",
      },
    ],
    name: "mulDiv",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "y",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "z",
        type: "uint256",
      },
    ],
    name: "mulDivRoundingUp",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610261806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80630af8b27f1461003b578063aa9a091214610076575b600080fd5b6100646004803603606081101561005157600080fd5b508035906020810135906040013561009f565b60408051918252519081900360200190f35b6100646004803603606081101561008c57600080fd5b50803590602081013590604001356100d9565b600080600083806100ac57fe5b858709119050806100be5760006100c1565b60015b60ff166100cf8686866100ee565b0195945050505050565b60006100e68484846100ee565b949350505050565b60008060006100fd868661018e565b915091506000848061010b57fe5b86880990508281111561011f576001820391505b8083039250848210610178576040805162461bcd60e51b815260206004820152601a60248201527f46756c6c4d6174683a2046554c4c4449565f4f564552464c4f57000000000000604482015290519081900360640190fd5b6101838383876101bb565b979650505050505050565b60008080600019848609905083850292508281039150828110156101b3576001820391505b509250929050565b600081810382168083816101cb57fe5b0492508085816101d757fe5b0494508081600003816101e657fe5b6002858103808702820302808702820302808702820302808702820302808702820302808702820302958602900390940293046001019390930293909301029291505056fea264697066735822122022584fe4f7508e07b6beb9b15bd67473c70a11cdfbcd50ddb849d06018d1066a64736f6c63430007060033";
