/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface BitMathEchidnaTestInterface extends ethers.utils.Interface {
  functions: {
    "leastSignificantBitInvariant(uint256)": FunctionFragment;
    "mostSignificantBitInvariant(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "leastSignificantBitInvariant",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mostSignificantBitInvariant",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "leastSignificantBitInvariant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mostSignificantBitInvariant",
    data: BytesLike
  ): Result;

  events: {};
}

export class BitMathEchidnaTest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: BitMathEchidnaTestInterface;

  functions: {
    leastSignificantBitInvariant(
      input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    "leastSignificantBitInvariant(uint256)"(
      input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    mostSignificantBitInvariant(
      input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    "mostSignificantBitInvariant(uint256)"(
      input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;
  };

  leastSignificantBitInvariant(
    input: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "leastSignificantBitInvariant(uint256)"(
    input: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  mostSignificantBitInvariant(
    input: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "mostSignificantBitInvariant(uint256)"(
    input: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    leastSignificantBitInvariant(
      input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "leastSignificantBitInvariant(uint256)"(
      input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    mostSignificantBitInvariant(
      input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "mostSignificantBitInvariant(uint256)"(
      input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    leastSignificantBitInvariant(
      input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "leastSignificantBitInvariant(uint256)"(
      input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mostSignificantBitInvariant(
      input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "mostSignificantBitInvariant(uint256)"(
      input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    leastSignificantBitInvariant(
      input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "leastSignificantBitInvariant(uint256)"(
      input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mostSignificantBitInvariant(
      input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "mostSignificantBitInvariant(uint256)"(
      input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
