/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface SqrtPriceMathTestInterface extends ethers.utils.Interface {
  functions: {
    "getAmount0Delta(uint160,uint160,uint128,bool)": FunctionFragment;
    "getAmount1Delta(uint160,uint160,uint128,bool)": FunctionFragment;
    "getGasCostOfGetAmount0Delta(uint160,uint160,uint128,bool)": FunctionFragment;
    "getGasCostOfGetAmount1Delta(uint160,uint160,uint128,bool)": FunctionFragment;
    "getGasCostOfGetNextSqrtPriceFromInput(uint160,uint128,uint256,bool)": FunctionFragment;
    "getGasCostOfGetNextSqrtPriceFromOutput(uint160,uint128,uint256,bool)": FunctionFragment;
    "getNextSqrtPriceFromInput(uint160,uint128,uint256,bool)": FunctionFragment;
    "getNextSqrtPriceFromOutput(uint160,uint128,uint256,bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAmount0Delta",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getAmount1Delta",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getGasCostOfGetAmount0Delta",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getGasCostOfGetAmount1Delta",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getGasCostOfGetNextSqrtPriceFromInput",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getGasCostOfGetNextSqrtPriceFromOutput",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getNextSqrtPriceFromInput",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getNextSqrtPriceFromOutput",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAmount0Delta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAmount1Delta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGasCostOfGetAmount0Delta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGasCostOfGetAmount1Delta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGasCostOfGetNextSqrtPriceFromInput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGasCostOfGetNextSqrtPriceFromOutput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNextSqrtPriceFromInput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNextSqrtPriceFromOutput",
    data: BytesLike
  ): Result;

  events: {};
}

export class SqrtPriceMathTest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: SqrtPriceMathTestInterface;

  functions: {
    getAmount0Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<{
      amount0: BigNumber;
      0: BigNumber;
    }>;

    "getAmount0Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<{
      amount0: BigNumber;
      0: BigNumber;
    }>;

    getAmount1Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<{
      amount1: BigNumber;
      0: BigNumber;
    }>;

    "getAmount1Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<{
      amount1: BigNumber;
      0: BigNumber;
    }>;

    getGasCostOfGetAmount0Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getGasCostOfGetAmount0Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getGasCostOfGetAmount1Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getGasCostOfGetAmount1Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getGasCostOfGetNextSqrtPriceFromInput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getGasCostOfGetNextSqrtPriceFromInput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getGasCostOfGetNextSqrtPriceFromOutput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getGasCostOfGetNextSqrtPriceFromOutput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getNextSqrtPriceFromInput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<{
      sqrtQ: BigNumber;
      0: BigNumber;
    }>;

    "getNextSqrtPriceFromInput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<{
      sqrtQ: BigNumber;
      0: BigNumber;
    }>;

    getNextSqrtPriceFromOutput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<{
      sqrtQ: BigNumber;
      0: BigNumber;
    }>;

    "getNextSqrtPriceFromOutput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<{
      sqrtQ: BigNumber;
      0: BigNumber;
    }>;
  };

  getAmount0Delta(
    sqrtLower: BigNumberish,
    sqrtUpper: BigNumberish,
    liquidity: BigNumberish,
    roundUp: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getAmount0Delta(uint160,uint160,uint128,bool)"(
    sqrtLower: BigNumberish,
    sqrtUpper: BigNumberish,
    liquidity: BigNumberish,
    roundUp: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getAmount1Delta(
    sqrtLower: BigNumberish,
    sqrtUpper: BigNumberish,
    liquidity: BigNumberish,
    roundUp: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getAmount1Delta(uint160,uint160,uint128,bool)"(
    sqrtLower: BigNumberish,
    sqrtUpper: BigNumberish,
    liquidity: BigNumberish,
    roundUp: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getGasCostOfGetAmount0Delta(
    sqrtLower: BigNumberish,
    sqrtUpper: BigNumberish,
    liquidity: BigNumberish,
    roundUp: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getGasCostOfGetAmount0Delta(uint160,uint160,uint128,bool)"(
    sqrtLower: BigNumberish,
    sqrtUpper: BigNumberish,
    liquidity: BigNumberish,
    roundUp: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getGasCostOfGetAmount1Delta(
    sqrtLower: BigNumberish,
    sqrtUpper: BigNumberish,
    liquidity: BigNumberish,
    roundUp: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getGasCostOfGetAmount1Delta(uint160,uint160,uint128,bool)"(
    sqrtLower: BigNumberish,
    sqrtUpper: BigNumberish,
    liquidity: BigNumberish,
    roundUp: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getGasCostOfGetNextSqrtPriceFromInput(
    sqrtP: BigNumberish,
    liquidity: BigNumberish,
    amountIn: BigNumberish,
    zeroForOne: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getGasCostOfGetNextSqrtPriceFromInput(uint160,uint128,uint256,bool)"(
    sqrtP: BigNumberish,
    liquidity: BigNumberish,
    amountIn: BigNumberish,
    zeroForOne: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getGasCostOfGetNextSqrtPriceFromOutput(
    sqrtP: BigNumberish,
    liquidity: BigNumberish,
    amountOut: BigNumberish,
    zeroForOne: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getGasCostOfGetNextSqrtPriceFromOutput(uint160,uint128,uint256,bool)"(
    sqrtP: BigNumberish,
    liquidity: BigNumberish,
    amountOut: BigNumberish,
    zeroForOne: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getNextSqrtPriceFromInput(
    sqrtP: BigNumberish,
    liquidity: BigNumberish,
    amountIn: BigNumberish,
    zeroForOne: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getNextSqrtPriceFromInput(uint160,uint128,uint256,bool)"(
    sqrtP: BigNumberish,
    liquidity: BigNumberish,
    amountIn: BigNumberish,
    zeroForOne: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getNextSqrtPriceFromOutput(
    sqrtP: BigNumberish,
    liquidity: BigNumberish,
    amountOut: BigNumberish,
    zeroForOne: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getNextSqrtPriceFromOutput(uint160,uint128,uint256,bool)"(
    sqrtP: BigNumberish,
    liquidity: BigNumberish,
    amountOut: BigNumberish,
    zeroForOne: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    getAmount0Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAmount0Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAmount1Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAmount1Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGasCostOfGetAmount0Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGasCostOfGetAmount0Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGasCostOfGetAmount1Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGasCostOfGetAmount1Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGasCostOfGetNextSqrtPriceFromInput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGasCostOfGetNextSqrtPriceFromInput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGasCostOfGetNextSqrtPriceFromOutput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGasCostOfGetNextSqrtPriceFromOutput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNextSqrtPriceFromInput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getNextSqrtPriceFromInput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNextSqrtPriceFromOutput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getNextSqrtPriceFromOutput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getAmount0Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAmount0Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAmount1Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAmount1Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGasCostOfGetAmount0Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGasCostOfGetAmount0Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGasCostOfGetAmount1Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGasCostOfGetAmount1Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGasCostOfGetNextSqrtPriceFromInput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGasCostOfGetNextSqrtPriceFromInput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGasCostOfGetNextSqrtPriceFromOutput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGasCostOfGetNextSqrtPriceFromOutput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNextSqrtPriceFromInput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getNextSqrtPriceFromInput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNextSqrtPriceFromOutput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getNextSqrtPriceFromOutput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getAmount0Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAmount0Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAmount1Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAmount1Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGasCostOfGetAmount0Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getGasCostOfGetAmount0Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGasCostOfGetAmount1Delta(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getGasCostOfGetAmount1Delta(uint160,uint160,uint128,bool)"(
      sqrtLower: BigNumberish,
      sqrtUpper: BigNumberish,
      liquidity: BigNumberish,
      roundUp: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGasCostOfGetNextSqrtPriceFromInput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getGasCostOfGetNextSqrtPriceFromInput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGasCostOfGetNextSqrtPriceFromOutput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getGasCostOfGetNextSqrtPriceFromOutput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNextSqrtPriceFromInput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getNextSqrtPriceFromInput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountIn: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNextSqrtPriceFromOutput(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getNextSqrtPriceFromOutput(uint160,uint128,uint256,bool)"(
      sqrtP: BigNumberish,
      liquidity: BigNumberish,
      amountOut: BigNumberish,
      zeroForOne: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
