/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface SwapMathEchidnaTestInterface extends ethers.utils.Interface {
  functions: {
    "checkComputeSwapStepInvariants(uint160,uint160,uint128,int256,uint24)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "checkComputeSwapStepInvariants",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkComputeSwapStepInvariants",
    data: BytesLike
  ): Result;

  events: {};
}

export class SwapMathEchidnaTest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: SwapMathEchidnaTestInterface;

  functions: {
    checkComputeSwapStepInvariants(
      sqrtPriceRaw: BigNumberish,
      sqrtPriceTargetRaw: BigNumberish,
      liquidity: BigNumberish,
      amountRemaining: BigNumberish,
      feePips: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    "checkComputeSwapStepInvariants(uint160,uint160,uint128,int256,uint24)"(
      sqrtPriceRaw: BigNumberish,
      sqrtPriceTargetRaw: BigNumberish,
      liquidity: BigNumberish,
      amountRemaining: BigNumberish,
      feePips: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;
  };

  checkComputeSwapStepInvariants(
    sqrtPriceRaw: BigNumberish,
    sqrtPriceTargetRaw: BigNumberish,
    liquidity: BigNumberish,
    amountRemaining: BigNumberish,
    feePips: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "checkComputeSwapStepInvariants(uint160,uint160,uint128,int256,uint24)"(
    sqrtPriceRaw: BigNumberish,
    sqrtPriceTargetRaw: BigNumberish,
    liquidity: BigNumberish,
    amountRemaining: BigNumberish,
    feePips: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    checkComputeSwapStepInvariants(
      sqrtPriceRaw: BigNumberish,
      sqrtPriceTargetRaw: BigNumberish,
      liquidity: BigNumberish,
      amountRemaining: BigNumberish,
      feePips: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "checkComputeSwapStepInvariants(uint160,uint160,uint128,int256,uint24)"(
      sqrtPriceRaw: BigNumberish,
      sqrtPriceTargetRaw: BigNumberish,
      liquidity: BigNumberish,
      amountRemaining: BigNumberish,
      feePips: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    checkComputeSwapStepInvariants(
      sqrtPriceRaw: BigNumberish,
      sqrtPriceTargetRaw: BigNumberish,
      liquidity: BigNumberish,
      amountRemaining: BigNumberish,
      feePips: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "checkComputeSwapStepInvariants(uint160,uint160,uint128,int256,uint24)"(
      sqrtPriceRaw: BigNumberish,
      sqrtPriceTargetRaw: BigNumberish,
      liquidity: BigNumberish,
      amountRemaining: BigNumberish,
      feePips: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    checkComputeSwapStepInvariants(
      sqrtPriceRaw: BigNumberish,
      sqrtPriceTargetRaw: BigNumberish,
      liquidity: BigNumberish,
      amountRemaining: BigNumberish,
      feePips: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "checkComputeSwapStepInvariants(uint160,uint160,uint128,int256,uint24)"(
      sqrtPriceRaw: BigNumberish,
      sqrtPriceTargetRaw: BigNumberish,
      liquidity: BigNumberish,
      amountRemaining: BigNumberish,
      feePips: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
