/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TickOverflowSafetyEchidnaTestInterface
  extends ethers.utils.Interface {
  functions: {
    "increaseFeeGrowthGlobal0X128(uint256)": FunctionFragment;
    "increaseFeeGrowthGlobal1X128(uint256)": FunctionFragment;
    "moveToTick(int24)": FunctionFragment;
    "setPosition(int24,int24,int128)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "increaseFeeGrowthGlobal0X128",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseFeeGrowthGlobal1X128",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "moveToTick",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPosition",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "increaseFeeGrowthGlobal0X128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseFeeGrowthGlobal1X128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "moveToTick", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPosition",
    data: BytesLike
  ): Result;

  events: {};
}

export class TickOverflowSafetyEchidnaTest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TickOverflowSafetyEchidnaTestInterface;

  functions: {
    increaseFeeGrowthGlobal0X128(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "increaseFeeGrowthGlobal0X128(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    increaseFeeGrowthGlobal1X128(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "increaseFeeGrowthGlobal1X128(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    moveToTick(
      target: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "moveToTick(int24)"(
      target: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setPosition(
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      liquidityDelta: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setPosition(int24,int24,int128)"(
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      liquidityDelta: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  increaseFeeGrowthGlobal0X128(
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "increaseFeeGrowthGlobal0X128(uint256)"(
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  increaseFeeGrowthGlobal1X128(
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "increaseFeeGrowthGlobal1X128(uint256)"(
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  moveToTick(
    target: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "moveToTick(int24)"(
    target: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setPosition(
    tickLower: BigNumberish,
    tickUpper: BigNumberish,
    liquidityDelta: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setPosition(int24,int24,int128)"(
    tickLower: BigNumberish,
    tickUpper: BigNumberish,
    liquidityDelta: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    increaseFeeGrowthGlobal0X128(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "increaseFeeGrowthGlobal0X128(uint256)"(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    increaseFeeGrowthGlobal1X128(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "increaseFeeGrowthGlobal1X128(uint256)"(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    moveToTick(target: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "moveToTick(int24)"(
      target: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setPosition(
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      liquidityDelta: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setPosition(int24,int24,int128)"(
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      liquidityDelta: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    increaseFeeGrowthGlobal0X128(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "increaseFeeGrowthGlobal0X128(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    increaseFeeGrowthGlobal1X128(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "increaseFeeGrowthGlobal1X128(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    moveToTick(target: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "moveToTick(int24)"(
      target: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setPosition(
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      liquidityDelta: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setPosition(int24,int24,int128)"(
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      liquidityDelta: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    increaseFeeGrowthGlobal0X128(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "increaseFeeGrowthGlobal0X128(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    increaseFeeGrowthGlobal1X128(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "increaseFeeGrowthGlobal1X128(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    moveToTick(
      target: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "moveToTick(int24)"(
      target: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setPosition(
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      liquidityDelta: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setPosition(int24,int24,int128)"(
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      liquidityDelta: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
