/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TickEchidnaTestInterface extends ethers.utils.Interface {
  functions: {
    "checkTickSpacingToParametersInvariants(int24)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "checkTickSpacingToParametersInvariants",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkTickSpacingToParametersInvariants",
    data: BytesLike
  ): Result;

  events: {};
}

export class TickEchidnaTest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TickEchidnaTestInterface;

  functions: {
    checkTickSpacingToParametersInvariants(
      tickSpacing: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    "checkTickSpacingToParametersInvariants(int24)"(
      tickSpacing: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;
  };

  checkTickSpacingToParametersInvariants(
    tickSpacing: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "checkTickSpacingToParametersInvariants(int24)"(
    tickSpacing: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    checkTickSpacingToParametersInvariants(
      tickSpacing: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "checkTickSpacingToParametersInvariants(int24)"(
      tickSpacing: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    checkTickSpacingToParametersInvariants(
      tickSpacing: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "checkTickSpacingToParametersInvariants(int24)"(
      tickSpacing: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    checkTickSpacingToParametersInvariants(
      tickSpacing: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "checkTickSpacingToParametersInvariants(int24)"(
      tickSpacing: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
