/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TickBitmapEchidnaTestInterface extends ethers.utils.Interface {
  functions: {
    "checkNextInitializedTickWithinOneWordInvariants(int24,bool)": FunctionFragment;
    "flipTick(int24)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "checkNextInitializedTickWithinOneWordInvariants",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "flipTick",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkNextInitializedTickWithinOneWordInvariants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "flipTick", data: BytesLike): Result;

  events: {};
}

export class TickBitmapEchidnaTest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TickBitmapEchidnaTestInterface;

  functions: {
    checkNextInitializedTickWithinOneWordInvariants(
      tick: BigNumberish,
      lte: boolean,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    "checkNextInitializedTickWithinOneWordInvariants(int24,bool)"(
      tick: BigNumberish,
      lte: boolean,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    flipTick(
      tick: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "flipTick(int24)"(
      tick: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  checkNextInitializedTickWithinOneWordInvariants(
    tick: BigNumberish,
    lte: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  "checkNextInitializedTickWithinOneWordInvariants(int24,bool)"(
    tick: BigNumberish,
    lte: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  flipTick(
    tick: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "flipTick(int24)"(
    tick: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    checkNextInitializedTickWithinOneWordInvariants(
      tick: BigNumberish,
      lte: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "checkNextInitializedTickWithinOneWordInvariants(int24,bool)"(
      tick: BigNumberish,
      lte: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    flipTick(tick: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "flipTick(int24)"(
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    checkNextInitializedTickWithinOneWordInvariants(
      tick: BigNumberish,
      lte: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "checkNextInitializedTickWithinOneWordInvariants(int24,bool)"(
      tick: BigNumberish,
      lte: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    flipTick(tick: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "flipTick(int24)"(
      tick: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    checkNextInitializedTickWithinOneWordInvariants(
      tick: BigNumberish,
      lte: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "checkNextInitializedTickWithinOneWordInvariants(int24,bool)"(
      tick: BigNumberish,
      lte: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    flipTick(
      tick: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "flipTick(int24)"(
      tick: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
