/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TickMathEchidnaTestInterface extends ethers.utils.Interface {
  functions: {
    "checkGetSqrtRatioAtTickInvariants(int24)": FunctionFragment;
    "checkGetTickAtSqrtRatioInvariants(uint160)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "checkGetSqrtRatioAtTickInvariants",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkGetTickAtSqrtRatioInvariants",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkGetSqrtRatioAtTickInvariants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkGetTickAtSqrtRatioInvariants",
    data: BytesLike
  ): Result;

  events: {};
}

export class TickMathEchidnaTest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TickMathEchidnaTestInterface;

  functions: {
    checkGetSqrtRatioAtTickInvariants(
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    "checkGetSqrtRatioAtTickInvariants(int24)"(
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    checkGetTickAtSqrtRatioInvariants(
      ratio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    "checkGetTickAtSqrtRatioInvariants(uint160)"(
      ratio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;
  };

  checkGetSqrtRatioAtTickInvariants(
    tick: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "checkGetSqrtRatioAtTickInvariants(int24)"(
    tick: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  checkGetTickAtSqrtRatioInvariants(
    ratio: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "checkGetTickAtSqrtRatioInvariants(uint160)"(
    ratio: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    checkGetSqrtRatioAtTickInvariants(
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "checkGetSqrtRatioAtTickInvariants(int24)"(
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    checkGetTickAtSqrtRatioInvariants(
      ratio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "checkGetTickAtSqrtRatioInvariants(uint160)"(
      ratio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    checkGetSqrtRatioAtTickInvariants(
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "checkGetSqrtRatioAtTickInvariants(int24)"(
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkGetTickAtSqrtRatioInvariants(
      ratio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "checkGetTickAtSqrtRatioInvariants(uint160)"(
      ratio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    checkGetSqrtRatioAtTickInvariants(
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "checkGetSqrtRatioAtTickInvariants(int24)"(
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkGetTickAtSqrtRatioInvariants(
      ratio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "checkGetTickAtSqrtRatioInvariants(uint160)"(
      ratio: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
